/* Generated by scripts/generate-typert.mjs in the emission format of
 * @deepseek-ai/dsh-typert-generator -- do not edit. See docs/decisions.md D11. */
import { z } from "zod";

export const TYPERT = {
  "package": "dsh-plugin-framework",
  "face": "host",
  "schemas": [],
  "invocations": [
    {
      "id": "dsh-plugin-framework#greeting/getGreeting",
      "service": "greeting",
      "namespace": "greeting",
      "method": "getGreeting",
      "invocation": {
        "kind": "direct"
      },
      "parameters": [],
      "result": {
        "mode": "strict",
        "typeSymbol": "dsh-plugin-framework/types#GreetingValue",
        "schema": z.string()
      },
      "sourceLocation": {
        "file": "src/features/hello-settings/api/remote.ts",
        "line": 23,
        "column": 3
      }
    },
    {
      "id": "dsh-plugin-framework#greeting/setGreeting",
      "service": "greeting",
      "namespace": "greeting",
      "method": "setGreeting",
      "invocation": {
        "kind": "direct"
      },
      "parameters": [
        {
          "name": "value",
          "wire": "value",
          "source": "json",
          "codec": {
            "mode": "strict",
            "typeSymbol": "dsh-plugin-framework/types#GreetingValue",
            "schema": z.string()
          }
        }
      ],
      "result": {
        "mode": "strict",
        "typeSymbol": "dsh-plugin-framework/types#GreetingValue",
        "schema": z.string()
      },
      "sourceLocation": {
        "file": "src/features/hello-settings/api/remote.ts",
        "line": 28,
        "column": 3
      }
    }
  ],
  "model": {
    "services": [],
    "events": [],
    "objects": []
  }
};
