/* Generated by scripts/generate-typert.mjs in the emission format of
 * @deepseek-ai/dsh-typert-generator -- do not edit. See docs/decisions.md D11. */
import type {
  RemoteResult,
  TypertRemoteContribution,
} from "@deepseek-ai/dsh-typert-protocol";

declare module "@deepseek-ai/dsh-typert-protocol" {
  interface TypertRemoteNamespace$6772656574696e67 {
    getGreeting: () => Promise<RemoteResult<string>>
    setGreeting: (value: string) => Promise<RemoteResult<string>>
  }
  interface TypertRemoteMap {
    'greeting/getGreeting': () => Promise<RemoteResult<string>>
    'greeting/setGreeting': (value: string) => Promise<RemoteResult<string>>
  }
  interface TypertRemoteNamespaceMap {
    "greeting": TypertRemoteNamespace$6772656574696e67
  }
}

export declare const TYPERT_REMOTE: TypertRemoteContribution;
export default TYPERT_REMOTE;
